[package]
name = "jsx-dom-expressions"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
convert_case = "0.6"
once_cell = "1.17"
regex = "1.8"
html-escape = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
string_cache = "0.8"
swc_atoms = "0.5"
swc_core = { version = "0.76", features = [
  "ecma_plugin_transform",
  "ecma_utils",
  "ecma_minifier",
  "ecma_visit",
  "ecma_ast",
  "common",
] }

[dev-dependencies]
testing = "0.33"
swc_core = { version = "0.76", features = ["testing_transform", "ecma_parser"] }
