[package]
name = "jsx-dom-expressions"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
convert_case = "0.6"
once_cell = "1.18"
regex = "1.8"
html-escape = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
string_cache = "0.8"
swc_atoms = { path = "../swc/crates/swc_atoms" }
swc_core = { path = "../swc/crates/swc_core", features = [
  "ecma_plugin_transform",
  "ecma_utils",
  "ecma_minifier",
  "ecma_visit",
  "ecma_ast",
  "common",
] }

[dev-dependencies]
testing = { path = "../swc/crates/testing" }
swc_core = { path = "../swc/crates/swc_core", features = [
  "testing_transform",
  "ecma_parser",
] }

# [patch.crates-io]
# swc_core = { path = "../swc/crates/swc_core" }
